#!/usr/bin/env python3
"""Regenerate `complete.lean`, a flattened, self-contained version of the library.

Run from the repository root:  python3 scripts/mk_complete.py

`complete.lean` concatenates the hand-written modules in dependency order and
splices in the two generated modules `real_align` needs: all of
`hol_up_real_terms` (the HOL Light definitions up to `real`) and only those
`hol_up_real_opam` axioms that are actually referenced.  Both stay inside their
original namespaces, opened for the `real_align` section alone, so that the
aligned `Real` operations defined there are the ones `after_real` sees.
"""

import os
import re

SRC = "HolLightLean"
HAND = ["conectors", "meta", "up_to_real"]
DROP = ("import ", "open HolLightLean.", "namespace HolLightLean.", "set_option linter.")
GUIDELINES = "-- Writing guidelines: https://leanprover-community.github.io/contribute/style.html"


def body(name):
    """The contents of a module, minus its imports, namespace and linter options."""
    lines = open(os.path.join(SRC, name + ".lean")).read().split("\n")
    return [l for l in lines if not l.strip().startswith(DROP) and l.strip() != GUIDELINES]


def used_axioms():
    """The `hol_up_real_opam` axioms referenced by the aligned modules."""
    text = "".join(open(os.path.join(SRC, f + ".lean")).read() for f in ["real_align", "after_real"])
    needed = set(re.findall(r"\bthm_[A-Za-z0-9_']+", text))
    kept = []
    for l in open(os.path.join(SRC, "hol_up_real_opam.lean")).read().split("\n"):
        m = re.match(r"axiom ([A-Za-z0-9_']+)", l)
        if m and m.group(1) in needed:
            kept.append(l)
            needed.discard(m.group(1))
    assert not needed, "referenced but not found in hol_up_real_opam: " + ", ".join(sorted(needed))
    return kept


opam = used_axioms()
out = [GUIDELINES,
       "-- AUTO-GENERATED by scripts/mk_complete.py -- do not edit by hand.",
       "-- Flattened, self-contained version of the HolLightLean library:",
       "--   conectors -> meta -> up_to_real -> real_align -> after_real",
       "-- together with the generated declarations `real_align` depends on.",
       "",
       "import Mathlib",
       "",
       "set_option linter.style.longLine false",
       "set_option linter.unusedVariables false",
       "set_option linter.style.missingEnd false",
       "set_option relaxedAutoImplicit false",
       "set_option maxSynthPendingDepth 3",
       ""]

for f in HAND:
    out += [f"/-! ### {f}.lean -/", ""] + body(f) + [""]

out += ["/-! ### hol_up_real_terms.lean (generated: the HOL Light definitions up to `real`) -/", "",
        "namespace HolLightLean.hol_up_real_terms", "open real", ""]
out += body("hol_up_real_terms")
out += ["", "end HolLightLean.hol_up_real_terms", ""]

out += [f"/-! ### hol_up_real_opam.lean ({len(opam)} generated HOL Light theorems, assumed as axioms) -/", "",
        "namespace HolLightLean.hol_up_real_opam", "open real", "open HolLightLean.hol_up_real_terms", ""]
out += opam
out += ["", "end HolLightLean.hol_up_real_opam", ""]

out += ["/-! ### real_align.lean -/", "",
        "section RealAlign",
        "open HolLightLean.hol_up_real_terms",
        "open HolLightLean.hol_up_real_opam", ""]
out += body("real_align")
out += ["", "end RealAlign", ""]

out += ["/-! ### after_real.lean -/", ""] + body("after_real") + [""]

open("complete.lean", "w").write("\n".join(out))
print(f"complete.lean: {len(out)} lines, {len(opam)} opam axioms spliced in")
